"""
## ============================================##
##  Header of QF/tools/exit_codes.py           ##
## ============================================##

## ============================================##
## Brief                                       ##
## Contains Exit Codes for responds.           ##
## ============================================##
"""

GATHER_SOCKET_INFORMATION_SUCCESS = (10, "Gather socket information is successed.")
GATHER_SOCKET_INFORMATION_FAILED = (-10, "Gather socket information is failed.")

GATHER_DEVICE_INFORMATION_SUCCESS = (20, "Gather device information is successed.")
GATHER_DEVICE_INFORMATION_FAILED = (-20, "Gather device information is failed.")

GATHER_CONNECTIVITY_INFORMATION_SUCCESS = (30, "Gather connectivity information is successed.")
GATHER_CONNECTIVITY_INFORMATION_FAILED = (-30, "Gather connectivity information is failed.")

GATHER_PORT_INFORMATION_SUCCESS = (40, "Gather socket information is successed.")
GATHER_PORT_INFORMATION_FAILED = (-40, "Gather socket information is failed.")

OPEN_COMMUNICATION_SUCCESS = (50, "Open communication is successfull.")
OPEN_COMMUNICATION_FAILED = (-50, "Open communication is failed.")

CLOSE_COMMUNICATION_SUCCESS = (51, "Close communication is successfull.")
CLOSE_COMMUNICATION_FAILED = (-51, "Close communication is failed.")

ACTIVATE_PORT_SUCCESS = (60, "Activate port is successfull.")
ACTIVATE_PORT_FAILED = (-60, "Activate port is failed.")

DEACTIVATE_PORT_SUCCESS = (61, "Deactivate port is successfull.")
DEACTIVATE_PORT_FAILED = (-61, "Deactivate port is failed.")

SOCKET_STATE_CHANGE_SUCCESS = (70, "Socket state change is successfull.")
SOCKET_STATE_CHANGE_FAILED = (-70, "Socket state change is failed.")

PAUSE_SOCKET_SUCCESS = (71, "Deactivate port is successfull.")
PAUSE_SOCKET_FAILED = (-71, "Deactivate port is failed.")

RESUME_SOCKET_SUCCESS = (72, "Deactivate port is successfull.")
RESUME_SOCKET_FAILED = (-72, "Deactivate port is failed.")

REFRESH_CONNECTION_SUCCESS = (80, "Refreshing connections is successfull.")
REFRESH_CONNECTION_FAILED = (-80, "Refreshing connections is failed.")

UNCONNECT_CHANNEL_SUCCESS = (90, "Unconnect channel is successfull.")
UNCONNECT_CHANNEL_FAILED = (-90, "Unconnect channel is failed.")

RECONNECT_CHANNEL_SUCCESS = (91, "Reconnect channel is successfull.")
RECONNECT_CHANNEL_FAILED = (-91, "Reconnect channel is failed.")

PING_CONNECTIONS_SUCCESS = (101, "Ping socket connections is successfull.")
PING_CONNECTIONS_FAILED = (-101, "Ping socket connections is failed.")

FIND_PORT_SUCCESS = (200, "Finding port is successed.")
FIND_PORT_FAILED = (-200, "Finding port is failed.")

PACKAGE_SENDED = (300, "Package is sended to target.")
QUPACK_SENDED = (301, "Qupack is sended to target.")
PACKAGE_IS_ROUTING = (450, "Package is sended with using routing.")
QUPACK_IS_ROUTING = (451, "Qupack is sended with using routing.")
BROADCASTED_PACKAGE = (400, "Package is broadcasted.")
NO_DIRECT_CONNECTION_FOUND = (-300, "No direct connection is found.")

PORT_IS_DISABLE = (-400, "Port is not active.")
ROUTING_IS_DISABLED = (-500, "Routing is disabled on this device")

FIND_CLASSIC_ROUTE_SUCCESS = (600, "Find classic route is success.")
FIND_CLASSIC_ROUTE_FAILED = (-600, "Find classic route is failed.")
FIND_QUANTUM_ROUTE_SUCCESS = (601, "Find quantum route is success.")
FIND_QUANTUM_ROUTE_FAILED = (-601, "Find quantum route is failed.")

SOCKET_IS_DONW_STATE = (-100, "Socket is down.")

GOT_PACKAGE = (105, "Got package from target.")
WAIT_PACKAGE_TIMEOUT = (-105, "Wait package timeout.")
GOT_QUBIT = (110, "Got package from target.")
WAIT_QUBIT_TIMEOUT = (-110, "Wait package timeout.")

GOT_LAYER_RESPOND = (121, "Got respond from layer.")
WAIT_RESPOND_TIMEOUT = (-121, "Wait respond timeout.")

ALLOCATE_QUBIT_SUCCESS = (150, "Allocate qubit successful.")
ALLOCATE_QUBIT_FAILED = (-150, "Allocate qubit failed.")

DEALLOCATE_QUBIT_SUCCESS = (160, "Allocate qubit successful.")
DEALLOCATE_QUBIT_FAILED = (-160, "Allocate qubit failed.")

MEASURE_QUBIT_SUCCESS = (180, "Measure qubit successful.")
MEASURE_QUBIT_FAILED = (-180, "Measure qubit failed.")

RESET_QUBIT_SUCCESS = (190, "Reset qubit successful.")
RESET_QUBIT_FAILED = (-190, "Reset qubit failed.")

PACKAGE_SENDED_COMFIRMED = (205, "Packege sended by device socket.")
PACKAGE_SEND_MAY_FAILED = (-205, "Packege sent may failed.")

QUANTUM_INFO_SENDED_COMFIRMED = (210, "Packege sended by device socket.")
QUANTUM_INFO_MAY_FAILED = (-210, "Packege sent may failed.")

GENERATE_EPR_SUCCESS = (220, "Generate epr pair successful.")
GENERATE_EPR_FAILED = (-220, "Generate epr pair is failed.")

GENERATE_GHZ_SUCCESS = (230, "Generate ghz pair successful.")
GENERATE_GHZ_FAILED = (-230, "Generate ghz pair is failed.")

SEND_EPR_SUCCESS = (240, "Send epr pair successful.")
SEND_EPR_FAILED = (-240, "Send epr pair is failed.")

SEND_GHZ_SUCCESS = (250, "Send ghz pair successful.")
SEND_GHZ_FAILED = (-250, "Send ghz pair is failed.")

QKD_LAYER_IS_NOT_AVAIBLE = (-270, "Qkd layer is not runnig.")
QKD_PROTOCOL_SUCCESS = (272, "Qkd layer ran protocol.")

exit_codes = {
    GATHER_SOCKET_INFORMATION_SUCCESS[0]: GATHER_SOCKET_INFORMATION_SUCCESS[1],
    GATHER_SOCKET_INFORMATION_FAILED[0]: GATHER_SOCKET_INFORMATION_FAILED[1],

    GATHER_DEVICE_INFORMATION_SUCCESS[0]: GATHER_DEVICE_INFORMATION_SUCCESS[1],
    GATHER_DEVICE_INFORMATION_FAILED[0]: GATHER_DEVICE_INFORMATION_FAILED[1],

    GATHER_CONNECTIVITY_INFORMATION_SUCCESS[0]: GATHER_CONNECTIVITY_INFORMATION_SUCCESS[1],
    GATHER_CONNECTIVITY_INFORMATION_FAILED[0]: GATHER_CONNECTIVITY_INFORMATION_FAILED[1],

    GATHER_PORT_INFORMATION_SUCCESS[0]: GATHER_PORT_INFORMATION_SUCCESS[1],
    GATHER_PORT_INFORMATION_FAILED[0]: GATHER_PORT_INFORMATION_FAILED[1],

    OPEN_COMMUNICATION_SUCCESS[0]: OPEN_COMMUNICATION_SUCCESS[1],
    OPEN_COMMUNICATION_FAILED[0]: OPEN_COMMUNICATION_FAILED[1],

    CLOSE_COMMUNICATION_SUCCESS[0]: CLOSE_COMMUNICATION_SUCCESS[1],
    CLOSE_COMMUNICATION_FAILED[0]: CLOSE_COMMUNICATION_FAILED[1],

    ACTIVATE_PORT_SUCCESS[0]: ACTIVATE_PORT_SUCCESS[1],
    ACTIVATE_PORT_FAILED[0]: ACTIVATE_PORT_FAILED[1],
    DEACTIVATE_PORT_FAILED[0]: DEACTIVATE_PORT_FAILED[1],

    SOCKET_STATE_CHANGE_SUCCESS[0]: SOCKET_STATE_CHANGE_SUCCESS[1],
    SOCKET_STATE_CHANGE_FAILED[0]: SOCKET_STATE_CHANGE_FAILED[1],

    PAUSE_SOCKET_SUCCESS[0]: PAUSE_SOCKET_SUCCESS[1],
    PAUSE_SOCKET_FAILED[0]: PAUSE_SOCKET_FAILED[1],

    RESUME_SOCKET_SUCCESS[0]: RESUME_SOCKET_SUCCESS[1],
    RESUME_SOCKET_FAILED[0]: RESUME_SOCKET_FAILED[1],

    REFRESH_CONNECTION_SUCCESS[0]: REFRESH_CONNECTION_SUCCESS[1],
    REFRESH_CONNECTION_FAILED[0]: REFRESH_CONNECTION_FAILED[1],

    UNCONNECT_CHANNEL_SUCCESS[0]: UNCONNECT_CHANNEL_SUCCESS[1],
    UNCONNECT_CHANNEL_FAILED[0]: UNCONNECT_CHANNEL_FAILED[1],

    RECONNECT_CHANNEL_SUCCESS[0]: RECONNECT_CHANNEL_SUCCESS[1],
    RECONNECT_CHANNEL_FAILED[0]: RECONNECT_CHANNEL_FAILED[1],

    PING_CONNECTIONS_SUCCESS[0]: PING_CONNECTIONS_SUCCESS[1],
    PING_CONNECTIONS_FAILED[0]: PING_CONNECTIONS_FAILED[1],

    FIND_PORT_SUCCESS[0]: FIND_PORT_SUCCESS[1],
    FIND_PORT_FAILED[0]: FIND_PORT_FAILED[1],

    PACKAGE_SENDED[0]: PACKAGE_SENDED[1],
    QUPACK_SENDED[0]: QUPACK_SENDED[1],
    PACKAGE_IS_ROUTING[0]: PACKAGE_IS_ROUTING[1],
    QUPACK_IS_ROUTING[0]: QUPACK_IS_ROUTING[1],
    BROADCASTED_PACKAGE[0]: BROADCASTED_PACKAGE[1],
    NO_DIRECT_CONNECTION_FOUND[0]: NO_DIRECT_CONNECTION_FOUND[1],

    PORT_IS_DISABLE[0]: PORT_IS_DISABLE[1],
    ROUTING_IS_DISABLED[0]: ROUTING_IS_DISABLED[1],

    FIND_CLASSIC_ROUTE_SUCCESS[0]: FIND_CLASSIC_ROUTE_SUCCESS[1],
    FIND_CLASSIC_ROUTE_FAILED[0]: FIND_CLASSIC_ROUTE_FAILED[1],
    FIND_QUANTUM_ROUTE_SUCCESS[0]: FIND_QUANTUM_ROUTE_SUCCESS[1],
    FIND_QUANTUM_ROUTE_FAILED[0]: FIND_QUANTUM_ROUTE_FAILED[1],

    SOCKET_IS_DONW_STATE[0]: SOCKET_IS_DONW_STATE[1],

    GOT_PACKAGE[0]: GOT_PACKAGE[1],
    WAIT_PACKAGE_TIMEOUT[0]: WAIT_PACKAGE_TIMEOUT[1],
    GOT_QUBIT[0]: GOT_QUBIT[1],
    WAIT_QUBIT_TIMEOUT[0]: WAIT_QUBIT_TIMEOUT[1],

    GOT_LAYER_RESPOND[0]: GOT_LAYER_RESPOND[1],
    WAIT_RESPOND_TIMEOUT[0]: WAIT_RESPOND_TIMEOUT[1],

    ALLOCATE_QUBIT_SUCCESS[0]: ALLOCATE_QUBIT_SUCCESS[1],
    ALLOCATE_QUBIT_FAILED[0]: ALLOCATE_QUBIT_FAILED[1],

    DEALLOCATE_QUBIT_SUCCESS[0]: DEALLOCATE_QUBIT_SUCCESS[1],
    DEALLOCATE_QUBIT_FAILED[0]: DEALLOCATE_QUBIT_FAILED[1],

    MEASURE_QUBIT_SUCCESS[0]: MEASURE_QUBIT_SUCCESS[1],
    MEASURE_QUBIT_FAILED[0]: MEASURE_QUBIT_FAILED[1],

    RESET_QUBIT_SUCCESS[0]: RESET_QUBIT_SUCCESS[1],
    RESET_QUBIT_FAILED[0]: RESET_QUBIT_FAILED[1],

    PACKAGE_SENDED_COMFIRMED[0]: PACKAGE_SENDED_COMFIRMED[1],
    PACKAGE_SEND_MAY_FAILED[0]: PACKAGE_SEND_MAY_FAILED[1],

    QUANTUM_INFO_SENDED_COMFIRMED[0]: QUANTUM_INFO_SENDED_COMFIRMED[1],
    QUANTUM_INFO_MAY_FAILED[0]: QUANTUM_INFO_MAY_FAILED[1],

    GENERATE_EPR_SUCCESS[0]: GENERATE_EPR_SUCCESS[1],
    GENERATE_EPR_FAILED[0]: GENERATE_EPR_FAILED[1],

    GENERATE_GHZ_SUCCESS[0]: GENERATE_GHZ_SUCCESS[1],
    GENERATE_GHZ_FAILED[0]: GENERATE_GHZ_FAILED[1],

    SEND_EPR_SUCCESS[0]: SEND_EPR_SUCCESS[1],
    SEND_EPR_FAILED[0]: SEND_EPR_FAILED[1],

    SEND_GHZ_SUCCESS[0]: SEND_GHZ_SUCCESS[1],
    SEND_GHZ_FAILED[0]: SEND_GHZ_FAILED[1],

    QKD_LAYER_IS_NOT_AVAIBLE[0]: QKD_LAYER_IS_NOT_AVAIBLE[1],
    QKD_PROTOCOL_SUCCESS[0]: QKD_PROTOCOL_SUCCESS[1],

}


def exit_code_desription(code: int):
    """Gets the description of exit code."""

    try:
        return exit_codes[code]
    except KeyError:
        return None
